language: android
dist: trusty

android:
  components:
    - tools
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-29"

cache:
  directories:
    - $HOME/.gradle

before_script:
  - chmod +x deploy_bintray.sh

script:
  - ./gradlew lintKotlin test

after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy_bintray.sh
