language: android

android:
  components:
    - tools
    - build-tools-26.0.1
    - android-26
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew test --info
